name: TopMineLeaderboard
api: [5.0.0]
version: 1.5.0+dev
author: reyyoga & AlvinHere
main: reyyoga\Main

commands:
 settopmine:
     description: set leaderboard location
permissions:
  settopmine.lb:
    description: topmineleaderboard permission!
    default: op
